#!/usr/bin/env bash

echo " Changing root bash to restricted admin cli..."

cp your_grace.runtime /etc/
chmod +x /etc/your_grace.runtime
cp your_grace.runtime /root/.bashrc

echo " Install complete!"
